### ISSUE TITLE
Add CI workflows

### ISSUE THREAD

**Issue by GaspardCulis** [outfoxxed/hy3#149]
Add a Github action to automatically build and test *hy3* on new commits and check branch changes before merging to main (this also means you'd have to develop/fix issues in specialized branches and submit a pull request in order to merge in main). This good practices would prevent some build errors that often occur when using the latest *hy3* commit on main in **flake inputs**,  **hy3-git** AUR package or **hyprpm**.

**Comment by outfoxxed** [comment]
All hy3 commits are tested locally before pushing already. Breakage happens due to upstream hyprland changes, as hyprland does not have a useful stable API surface. Because of this, I haven't set up CI.

If you want to write it, I would accept it, but I consider it largely a waste of time for this project.
