### ISSUE TITLE
hy3 disables cursor warping when focusing a window on the same workspace

### ISSUE THREAD

**Issue by AhuracMusic** [outfoxxed/hy3#57]
On default Hyprland, when focusing a window, whether it is on the same workspace as the previously focused one or on another, the cursor is warped to the center of the destination window. i3/Sway only warps the cursor to the center of a window if the destination window is on another workspace. hy3 seems to emulate this i3/Sway behaviour, but Hyprland already supports it via the configurtion variable `general:no_cursor_warp`, so I think hy3 should not override it.

EDIT: replaced "wrap" with "warp" everywhere 🤦

**Comment by BrianCArnold** [comment]
Also, +1 to this as an issue, although I would actually prefer to be able to have my cursor warp between windows when changing between windows in a workspace. Basically, I want "Always warp" rather than "Never warp". 

Ideally, a configuration option to allow configuration along the lines of `hy3:cursor_warp` with at least 3 settings:(

* 0: No cursor warping
* 1: Cursor Warping between workspaces
* 2: Cursor Warping between workspaces and windows.

**Comment by AhuracMusic** [comment]
> Note: This is actually called "Cursor Warping", rather than "Cursor Wrapping". The configuration variable is called `general:no_cursor_warps`
> 
> (Adding this comment both for correctness and so that other users will be able to find it by searching)

No way I'm realizing this now, how come I have been saying the wrong word for so long...

**Comment by outfoxxed** [comment]
that clears this up some, along with the comment. this would be because we use a custom dispatcher which dosen't do the same thing as the normal one. @BrianCArnold it would probably make sense to bring all 3 into hyprland itself and just use the same setting.

**Comment by BrianCArnold** [comment]
I actually think I was wrong with the three settings, I believe the standard settings as they stand in Hyprland may functionally mirror the settings desired, switching workspaces without warping the cursor doesn't seem to make much sense.

When switching from an active workspace to another workspace, I can't imagine there would often be a scenario where the desired behavior is leaving focus on the previous workspace and window.

In single display environments, when switching to a different workspace, the cursor is already effectively "changing position" because the window it was previously over would have already disappeared, as it was only visible on the other workspace.

In multiple display environments, it would be possible for the previous workspace to remain visible, however I would think that changing workspaces would (nearly) always imply changing window focus.

If the hy3 plugin simply changed to obey the existing warping setting, and warped the cursor to (any|the most recently focused window on that workspace) the two functional modes would be "cursor follows window focus on workspace change" and "cursor always follows window focus". I believe this should mirror both Sway and Hyprland functionality.

This approach would also not necessitate any additional settings in the schema, only requiring users who despire disabling warping to add the setting.

**Comment by BrianCArnold** [comment]
> > Note: [...]
> 
> No way I'm realizing this now, how come I have been saying the wrong word for so long...

Honestly, I've made the same mistake MANY times, it's kind of natural because of how close the words are. I think "cursor jumping" might have ended up causing less confusion, but for all I know that's a different feature I'm not using.

**Comment by BrianCArnold** [comment]
Here's my workaround to warp the mouse:

### In your binds (something like this, salt to taste):
```
bind = $mainMod, left, exec, ~/.config/hypr/scripts/MoveFocus.sh l
bind = $mainMod, right, exec, ~/.config/hypr/scripts/MoveFocus.sh r 
bind = $mainMod, down, exec, ~/.config/hypr/scripts/MoveFocus.sh d 
bind = $mainMod, up, exec, ~/.config/hypr/scripts/MoveFocus.sh u 
```
### `~/.config/hypr/scripts/MoveFocus.sh`
```
#!/bin/bash

hyprctl dispatch hy3:movefocus $1 >/dev/null

X=$(hyprctl activewindow -j | jq '(.size[0]/2 | floor) + .at[0]')
Y=$(hyprctl activewindow -j | jq '(.size[1]/2 | floor) + .at[1]')

hyprctl dispatch movecursor $X $Y >/dev/null
```

**Comment by outfoxxed** [comment]
Added in 311939d4439033cfdeb77dbc1dba0d689cef750b.

**Comment by AhuracMusic** [comment]
Thanks a lot for adding this feature!
